// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-Iz5b2gH0VXPbcpJzLm75OoWkd7JwEM',
    appId: '1:39512235521:web:c82d1cd78a2049c8dd6a00',
    messagingSenderId: '39512235521',
    projectId: 'chatapp-d8d86',
    authDomain: 'chatapp-d8d86.firebaseapp.com',
    storageBucket: 'chatapp-d8d86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA794ZQEQJ9_zAKbeI6UhH_ySUXGsU9gWM',
    appId: '1:39512235521:android:b1d219d9103d9285dd6a00',
    messagingSenderId: '39512235521',
    projectId: 'chatapp-d8d86',
    storageBucket: 'chatapp-d8d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcs-WyU4ljLofh7cATzcqDC5YSD8x5TI',
    appId: '1:39512235521:ios:88a659197588146cdd6a00',
    messagingSenderId: '39512235521',
    projectId: 'chatapp-d8d86',
    storageBucket: 'chatapp-d8d86.appspot.com',
    iosClientId: '39512235521-ahotpatvhpl3lrpupv0jflu77rqt3jc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlcs-WyU4ljLofh7cATzcqDC5YSD8x5TI',
    appId: '1:39512235521:ios:29b7bb7ac3351d34dd6a00',
    messagingSenderId: '39512235521',
    projectId: 'chatapp-d8d86',
    storageBucket: 'chatapp-d8d86.appspot.com',
    iosClientId: '39512235521-cesu80rd5kmqkqahu6babbj65o2oiut7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
